#!/usr/bin/env python3
"""Exact paired statistics for the real-user labeling study (Phase 4.6).

Given n=24 participants, normal-approximation Wilcoxon p-values are replaced by
EXACT tests:
  * accept-rate and coupling contrasts (baseline vs gaming / fatigue) use the
    exact conditional sign-flip permutation distribution of the signed-rank
    statistic (computed by exact convolution; handles ties from coarse
    per-participant accept rates, which preclude scipy's pure-exact mode);
  * baseline coupling positivity uses the exact binomial sign test.
Effect sizes are paired Cohen's d_z with 10k-bootstrap 95% CIs.

Reads out_real/{per_trial_with_pod.csv, coupling_per_participant.csv} and writes
out_real/macros_realuser.tex (\\input by the manuscript) plus a JSON summary.
"""
from __future__ import annotations
import json, os, sys
import numpy as np, pandas as pd
from scipy.stats import rankdata, binomtest

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "out_real")


def exact_signed_rank_p(diff):
    diff = np.asarray(diff, float); diff = diff[diff != 0]
    r = rankdata(np.abs(diff))                 # average ranks for ties
    r2 = np.rint(r * 2).astype(int)            # x2 -> integer half-ranks
    Tplus = int(np.rint(r[diff > 0].sum() * 2))
    total = int(r2.sum())
    dist = np.zeros(total + 1); dist[0] = 1.0
    for v in r2:                               # convolve {0, v} each at prob 1/2
        nd = dist * 0.5
        nd[v:] += dist[:total + 1 - v] * 0.5
        dist = nd
    p = min(1.0, 2 * min(dist[:Tplus + 1].sum(), dist[Tplus:].sum()))
    return float(p), len(diff)


def dz_ci(diff, nboot=10000, seed=0):
    diff = np.asarray(diff, float)
    sd = diff.std(ddof=1); dz = float(diff.mean() / sd)
    rng = np.random.default_rng(seed); n = len(diff); bs = np.empty(nboot)
    for i in range(nboot):
        s = diff[rng.integers(0, n, n)]; ss = s.std(ddof=1)
        bs[i] = s.mean() / ss if ss > 0 else 0.0
    return dz, float(np.quantile(bs, .025)), float(np.quantile(bs, .975))


def fmt_p(p):
    if p < 1e-4:
        from math import log10, floor
        e = floor(log10(p)); m = p / 10**e
        return f"{m:.1f}\\times10^{{{e}}}"
    if p < 0.1:
        return f"{p:.3f}".rstrip("0").rstrip(".") if p >= 0.001 else f"{p:.4f}"
    return f"{p:.2f}"


def main():
    tr = pd.read_csv(os.path.join(OUT, "per_trial_with_pod.csv"))
    cp = pd.read_csv(os.path.join(OUT, "coupling_per_participant.csv"))
    ar = tr.groupby(["participant_id", "induced_condition"])["pod_accept"].mean().unstack("induced_condition")
    piv = cp.pivot_table(index="participant_id", columns="induced_condition", values="spearman_rho")

    res = {}
    def contrast(tag, frame, cond):
        d = frame.dropna(subset=["baseline", cond])
        diff = (d["baseline"] - d[cond]).values
        p, n = exact_signed_rank_p(diff)
        dz, lo, hi = dz_ci(diff)
        res[tag] = dict(n=int(n), n_pos=int((diff > 0).sum()), exact_p=p,
                        dz=dz, dz_lo=lo, dz_hi=hi)

    contrast("accept_gaming", ar, "gaming")
    contrast("accept_fatigue", ar, "fatigue")
    contrast("coupling_gaming", piv, "gaming")
    contrast("coupling_fatigue", piv, "fatigue")

    base = piv.dropna(subset=["baseline"])["baseline"]
    npos = int((base > 0).sum()); n = int(base.size)
    res["coupling_pos"] = dict(n=n, n_pos=npos,
        sign_p_onesided=float(binomtest(npos, n, 0.5, alternative="greater").pvalue))

    # Holm correction over the five within-subject contrasts (Phase 6.3).
    fam = {"accept_fatigue": res["accept_fatigue"]["exact_p"],
           "accept_gaming": res["accept_gaming"]["exact_p"],
           "coupling_fatigue": res["coupling_fatigue"]["exact_p"],
           "coupling_gaming": res["coupling_gaming"]["exact_p"],
           "coupling_pos": res["coupling_pos"]["sign_p_onesided"]}
    order = sorted(fam, key=fam.get); m = len(order); prev = 0.0
    holm = {}
    for i, k in enumerate(order):
        adj = min(1.0, (m - i) * fam[k]); adj = max(adj, prev); prev = adj
        holm[k] = adj
    res["holm"] = holm

    with open(os.path.join(OUT, "realuser_exact_stats.json"), "w") as f:
        json.dump(res, f, indent=2)

    L = ["%% AUTO-GENERATED by scripts/realuser_stats.py -- exact paired tests (Phase 4.6).",
         "%% DO NOT hand-edit. Regenerate: python scripts/realuser_stats.py",
         f"\\newcommand{{\\RealFatigueAcceptP}}{{\\ensuremath{{{fmt_p(res['accept_fatigue']['exact_p'])}}}}}",
         f"\\newcommand{{\\RealFatigueAcceptDz}}{{\\ensuremath{{{res['accept_fatigue']['dz']:.2f}}}}}",
         f"\\newcommand{{\\RealFatigueAcceptCI}}{{\\ensuremath{{[{res['accept_fatigue']['dz_lo']:.2f},\\,{res['accept_fatigue']['dz_hi']:.2f}]}}}}",
         f"\\newcommand{{\\RealGamingAcceptP}}{{\\ensuremath{{{fmt_p(res['accept_gaming']['exact_p'])}}}}}",
         f"\\newcommand{{\\RealGamingAcceptDz}}{{\\ensuremath{{{res['accept_gaming']['dz']:.2f}}}}}",
         f"\\newcommand{{\\RealGamingAcceptCI}}{{\\ensuremath{{[{res['accept_gaming']['dz_lo']:.2f},\\,{res['accept_gaming']['dz_hi']:.2f}]}}}}",
         f"\\newcommand{{\\RealCouplingGamingP}}{{\\ensuremath{{{fmt_p(res['coupling_gaming']['exact_p'])}}}}}",
         f"\\newcommand{{\\RealCouplingFatigueP}}{{\\ensuremath{{{fmt_p(res['coupling_fatigue']['exact_p'])}}}}}",
         f"\\newcommand{{\\RealCouplingPosSignP}}{{\\ensuremath{{{fmt_p(res['coupling_pos']['sign_p_onesided'])}}}}}",
         f"\\newcommand{{\\RealFatigueAcceptPHolm}}{{\\ensuremath{{{fmt_p(res['holm']['accept_fatigue'])}}}}}",
         f"\\newcommand{{\\RealGamingAcceptPHolm}}{{\\ensuremath{{{fmt_p(res['holm']['accept_gaming'])}}}}}",
         f"\\newcommand{{\\RealCouplingFatiguePHolm}}{{\\ensuremath{{{fmt_p(res['holm']['coupling_fatigue'])}}}}}",
         f"\\newcommand{{\\RealCouplingGamingPHolm}}{{\\ensuremath{{{fmt_p(res['holm']['coupling_gaming'])}}}}}",
         f"\\newcommand{{\\RealCouplingPosPHolm}}{{\\ensuremath{{{fmt_p(res['holm']['coupling_pos'])}}}}}"]
    with open(os.path.join(OUT, "macros_realuser.tex"), "w") as f:
        f.write("\n".join(L) + "\n")

    print("[realuser_stats] exact paired tests:")
    for k, v in res.items():
        if "exact_p" in v:
            print(f"  {k:16s} n={v['n']} pos={v['n_pos']}/{v['n']} exact_p={v['exact_p']:.4g} "
                  f"d_z={v['dz']:.2f} CI[{v['dz_lo']:.2f},{v['dz_hi']:.2f}]")
    print(f"  coupling_pos {res['coupling_pos']['n_pos']}/{res['coupling_pos']['n']} "
          f"sign_p(one-sided)={res['coupling_pos']['sign_p_onesided']:.4g}")
    print("[realuser_stats] wrote out_real/macros_realuser.tex + realuser_exact_stats.json")


if __name__ == "__main__":
    main()
